
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-myservice
  labels:
    {{- include "mylabels" . }}  
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bakehouse
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
